name: Build and Release tag

on:
  push:
    tags:
      - v*

permissions:
  contents: write

env:  
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  tag: ${{ github.ref_name }}
  BUILD_APP_NAME: 'LPR stations data viewer'
      
jobs:
  pyinstaller-build:
    name: Build app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pycodestyle
      - name: DIR
        run: |
          dir D:\
      - name: PEP8 check
        run: |
          pycodestyle . --ignore E501,E722
      - name: Build an app
        run: |
          pyinstaller --noconfirm --clean --log-level FATAL --onedir --name "${BUILD_APP_NAME}" --contents-directory "." --noconsole --icon "icon.ico" --add-data "icon.ico";"." --add-data "settings.ini";"." "main.py"
          
  release:    
    name: Create release
    runs-on: ubuntu-22.04
    needs: pyinstaller-build
    steps:
      - name: Download builded app
        uses: actions/download-artifact@v4
        with:
          name: App
          path: .
      - name: Check the directory
        run: |
          ls -r .
      - name: Archive builded app
        run: |
          zip -r "${GITHUB_REPOSITORY#*/}.zip" "${BUILD_APP_NAME}"
      - name: Create release
        run: |
          gh release create "${tag}" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REPOSITORY#*/} ${tag}" \
              --generate-notes
      - name: Upload asset
        run: |
          gh release upload "${tag}" "${GITHUB_REPOSITORY#*/}.zip" \
          --repo="${GITHUB_REPOSITORY}" \
