name: Pylint
on: push
jobs:
  setup-python:
    runs-on: windows-latest
    steps: 
    - name: Setup Python 3.11
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.11'
